In [3]:
import numpy as np
import time
import sys

python_list = list(range(10000))
numpy_array = np.array(range(10000))
start = time.time()
doubled_list = [x*2 for x in python_list]
list_time = time.time() - start
print(f"czas dla listy python: {list_time:.4f}s")

start = time.time()
doubled_array = numpy_array *2
numpy_time = time.time() - start
print(f"Czas dla tablicy Numpy: {numpy_time:.4f}s")
speedup = list_time / numpy_time
print(f"\n Numpy jest {speedup:.1f}")


list_size = sys.getsizeof(python_list)
array_size = numpy_array.nbytes
print(f"\nRozmiar listy: {list_size / 1024:.1f} KB")
print(f"Rozmiar tablicy NumPy: {array_size / 1024:.1f} KB")
print(f"Oszczędność pamięci: {(1 - array_size/list_size)*100:.1f}%")


czas dla listy python: 0.0005s
Czas dla tablicy Numpy: 0.0001s

 Numpy jest 5.6

Rozmiar listy: 78.2 KB
Rozmiar tablicy NumPy: 78.1 KB
Oszczędność pamięci: 0.1%


In [10]:
arr_from_list = np.array([1, 2, 3, 4, 5])
print("Z listy:", arr_from_list)
print("Typ:"), type(arr_from_list)
print("Dtype", arr_from_list.dtype)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(f"\nTablica 2d:\n", arr_2d)
print(f"Shape:", arr_2d.shape)
print(f"Wymiary:", arr_2d.ndim)

zeros = np.zeros(5)
print(f"\nZeros:", zeros)

zeros_2d = np.zeros((3,4))
print("zera 2d:\n", zeros_2d)

ones = np.ones((2,3))
print("\nJedynki:\n", ones)

full = np.full((2,2), 7)
print(f"\nWypełnione 7: \n", full)

sek = np.arange(0,10,2)
print(f"Sekwencja:", sek)

linspace = np.linspace(0,1,5)
print(linspace)

identity = np.eye(3)
print(identity)

random_vals = np.random.rand(5)
print(random_vals)

random_ints = np.random.randint(1, 100, size =10)
print(random_ints)

float_array = np.array([1,2,3], dtype = np.float32)
print(float_array)

Z listy: [1 2 3 4 5]
Typ:
Dtype int64

Tablica 2d:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Wymiary: 2

Zeros: [0. 0. 0. 0. 0.]
zera 2d:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Jedynki:
 [[1. 1. 1.]
 [1. 1. 1.]]

Wypełnione 7: 
 [[7 7]
 [7 7]]
Sekwencja: [0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.68677527 0.99222476 0.0964349  0.47597191 0.74042737]
[30 65 42 92 77 84 12  1 35 86]
[1. 2. 3.]


### 1. Podstawy i konfiguracja
*   **`import numpy as np`** – standardowa konwencja importowania biblioteki do analizy danych [1].
*   **`np.__version__`** – zwraca aktualnie zainstalowaną wersję biblioteki NumPy [2].
*   **`np.show_config()`** – wyświetla szczegółowe informacje o konfiguracji biblioteki [2].

### 2. Tworzenie tablic
*   **`np.array()`** – tworzy nową tablicę NumPy (tzw. `ndarray`), na przykład ze standardowej listy Pythonowej lub listy zagnieżdżonej [3, 4].
*   **`np.zeros()`** – tworzy tablicę wypełnioną samymi zerami [4].
*   **`np.ones()`** – tworzy tablicę wypełnioną samymi jedynkami [4].
*   **`np.full()`** – tworzy tablicę, w której wszystkie elementy mają tę samą, zdefiniowaną wartość [4].
*   **`np.arange(start, stop, step)`** – generuje sekwencję liczb o określonym kroku, działając podobnie do wbudowanej funkcji `range()` [5].
*   **`np.linspace(start, stop, num)`** – tworzy wektor składający się z podanej liczby równoodległych od siebie wartości w określonym przedziale [5].
*   **`np.eye()`** – tworzy dwuwymiarową macierz identyczności, mającą jedynki na przekątnej [5].

### 3. Atrybuty tablic (właściwości obiektu ndarray)
*   **`arr.shape`** – zwraca kształt tablicy w postaci krotki, informując o liczbie elementów w każdym wymiarze [4].
*   **`arr.ndim`** – zwraca liczbę wymiarów danej tablicy [4].
*   **`arr.dtype`** – pozwala sprawdzić lub określić typ danych elementów tablicy, co bywa kluczowe przy optymalizacji pamięci [3, 6].
*   **`arr.nbytes`** – zwraca rozmiar tablicy w pamięci wyrażony w bajtach [7].

### 4. Modyfikowanie tablic
*   **`arr.reshape()`** – zmienia kształt tablicy bez ingerencji w zawarte w niej dane [6].
*   **`arr.copy()`** – wymusza utworzenie niezależnej w pamięci kopii tablicy, ponieważ standardowe wycinanie zwraca jedynie widok do oryginalnych danych [8].

### 5. Indeksowanie, filtrowanie i slicing
*   **`arr[indeks]`** lub **`arr[wiersz, kolumna]`** – wyciąga konkretny, pojedynczy element z tablicy 1D lub 2D [9, 10].
*   **`arr[start:stop:step]`** – (tzw. slicing) wycina i zwraca wybrany fragment tablicy [9].
*   **`arr[:, kolumna]`** – wycina wszystkie wiersze z wybranej kolumny, co jest użyteczne przy wydobywaniu konkretnych cech [11].
*   **Boolean indexing** – filtruje dane na podstawie maski logicznej, np. `arr[arr > 15]` [12].
*   **Fancy indexing** – przekazuje listę lub tablicę indeksów, aby wyciągnąć precyzyjnie wybrane elementy, np. `arr[[2, 13, 14]]` [15, 16].

### 6. Funkcje matematyczne (ufuncs) i operatory
*   **Operatory arytmetyczne (`+`, `-`, `*`, `/`, `//`, `%`, `**`)** – NumPy obsługuje wektorowo wszystkie klasyczne znaki działań [17].
*   **Operator `@`** – służy do mnożenia macierzowego (dot product) [18, 19].
*   **`np.sqrt()`** – oblicza pierwiastek kwadratowy ze wszystkich elementów tablicy [20].
*   **`np.square()`** – podnosi poszczególne wartości do kwadratu [20].
*   **`np.log()`** – oblicza logarytm naturalny elementów [20].
*   **`np.exp()`** – aplikuje funkcję eksponencjalną do każdego elementu [20].
*   **`np.sin()`, `np.cos()`, `np.pi`** – pozwalają na wyliczanie wartości funkcji trygonometrycznych dla kątów w radianach oraz udostępniają stałą Pi [21].
*   **`np.round()`, `np.floor()`, `np.ceil()`** – to funkcje operujące na zaokrąglaniu wartości (do najbliższej, w dół i w górę) [21].
*   **`np.abs()`** – zwraca wartość bezwzględną z przekazanych danych [21].
*   **`np.clip(tablica, min, max)`** – przycina wartości w tablicy tak, by nie przekraczały podanego przedziału [22].

### 7. Funkcje statystyczne i agregujące
Większość z tych funkcji wspiera argument **`axis`**, operujący wzdłuż kolumn (`axis=0`) lub wierszy (`axis=1`) [23, 24].
*   **`np.mean()`** – oblicza średnią arytmetyczną [22].
*   **`np.median()`** – oblicza medianę rozkładu [22].
*   **`np.std()`** – wylicza odchylenie standardowe ze zbioru [22].
*   **`np.min()`, `np.max()`** – szuka najmniejszej i największej wartości w dostępnej tablicy [22].
*   **`np.sum()`** – sumuje elementy, a przy tablicach logicznych może służyć do zliczania ilości spełnionych warunków [22, 23].
*   **`np.argmin()`, `np.argmax()`** – podają jako wynik indeks, pod którym znajduje się odpowiednio najmniejszy i największy element [25, 26].
*   **`np.percentile()`** – wylicza dany percentyl dla zbioru wartości [23].
*   **`np.unique()`** – zwraca listę unikalnych wartości występujących w datasecie [27].

### 8. Generowanie wartości losowych (moduł `np.random`)
*   **`np.random.rand()`** – generuje losowe wartości należące do przedziału `[0, 1)` [5].
*   **`np.random.randint()`** – tworzy losowe liczby całkowite ze wskazanego przez nas zakresu [5, 26].
*   **`np.random.randn()`** – losuje wartości z rozkładu normalnego [28].
*   **`np.random.seed()`** – definiuje ziarno losowości gwarantujące odtwarzalność wyników za każdym uruchomieniem [29].
*   **`np.random.shuffle()`** – pozwala w miejscu przetasować rozkład elementów w tablicy [30].

### 9. Pozostałe narzędzia
*   **`np.pad()`** – dodaje odpowiedni margines dookoła krawędzi wejściowej tablicy [19, 31].
*   **`np.concatenate()`** – pozwala na elastyczne łączenie różnych tablic ze sobą [30].
*   **`np.argsort()`** – zwraca tablicę indeksów w kolejności potrzebnej do posortowania elementów rosnąco [32].
*   **`np.column_stack()`** – złącza wejściowe tablice jednowymiarowe w pionie, tworząc gotowe kolumny dla nowej tablicy wielowymiarowej [32].
*  **`'Parametr axis jest kluczowy:'`**
*  **`axis=0 : operacja wzdłuż wierszy (kolapsuje wiersze → wynik per kolumna)`**
*  **`axis=1 : operacja wzdłuż kolumn (kolapsuje kolumny → wynik per wiersz)`**
* *  **`'Brak axis : operacja na całej tablicy'`**


1. ✏ Zadanie 1 – Tworzenie i analiza tablic
Utwórz tablicę NumPy zawierającą liczby od 1 do 100. Oblicz i wypisz:
Sumę wszystkich elementów
Średnią arytmetyczną
Medianę
Wartość maksymalną i minimalną
Wymagania:
Użyj np.arange() do stworzenia tablicy
Użyj funkcji agregujących NumPy ( np.sum, np.mean, etc.)
(proste)

2. ✏ Zadanie 2 – Operacje wektorowe
Masz dwie tablice reprezentujące ceny produktów przed i po rabacie:
before = np.array([100, 250, 75, 320, 180, 450, 90])
after = np.array([80, 200, 60, 280, 150, 400, 75])
Oblicz i wypisz:
Różnicę między cenami (oszczędności)
Procent rabatu dla każdego produktu
Średnią oszczędność
Wymagania:
Użyj operacji wektorowych (bez pętli)
Wynik zaokrąglij do 2 miejsc po przecinku
(proste)

3. ✏ Zadanie 3 – Indeksowanie i slicing
Dana tablica 1D:
temps = np.array([15, 18, 22, 25, 23, 20, 17, 14, 16, 19, 21, 24])
Wykonaj:
Wypisz temperatury z dni parzystych (0, 2, 4, ...)
Wypisz ostatnie 5 temperatur
Wypisz temperatury w odwrotnej kolejności
Znajdź temperatury większe niż 20
(proste)

4. ✏ Zadanie 4 – Tablice 2D
Utwórz tablicę 2D (5x4) wypełnioną losowymi liczbami całkowitymi od 1 do 50.
Wymagania:
Użyj np.random.randint()
Wypisz shape tablicy
Wypisz drugi wiersz
Wypisz trzecią kolumnę
Wypisz element z pozycji (2, 3)

5. ✏ Zadanie 5 – Statystyki per wiersz i kolumna
Dana tablica reprezentująca sprzedaż 4 produktów w 7 dni:
sales = np.random.randint(10, 100, size=(4, 7))
Oblicz i wypisz:
Średnią sprzedaż per produkt (axis=1)
Średnią sprzedaż per dzień (axis=0)
Dzień z najwyższą sprzedażą (np.argmax)
Produkt z najniższą średnią sprzedażą

6. ✏ Zadanie 6 – Boolean indexing
Masz tablicę z oceną studentów:
grades = np.array([78, 45, 92, 67, 34, 88, 56, 91, 23, 85, 73, 95])
Wykonaj:
Znajdź wszystkie oceny >= 80 (oceny wysokie)
Znajdź wszystkie oceny < 50 (oceny niedostateczne)
Policz ile jest ocen w przedziale [60, 80)
Zmień wszystkie oceny < 50 na 50 (podniesienie do minimum)
(proste)

7. ✏ Zadanie 7 – Tworzenie macierzy specjalnych
Utwórz następujące macierze:
Macierz 3x3 wypełnioną zerami
Macierz 4x4 wypełnioną jedynkami
Macierz identyczności 5x5
Macierz 3x4 wypełnioną liczbą 7
Wektor 10 równoodległych wartości od 0 do 1
Wymagania:
Użyj np.zeros, np.ones, np.eye, np.full, np.linspace

8. ✏ Zadanie 8 – Reshape i flatten
Dana tablica:
arr = np.arange(1, 13)
Wykonaj:
Zmień kształt na (3, 4)
Zmień kształt na (2, 6)
Zmień kształt na (4, 3)
Spłaszcz z powrotem do 1D (flatten lub ravel)
Wymagania:
Użyj metody .reshape()
Sprawdź różnicę między flatten() a ravel()

Zadania średnie (9-12)
9. ✏ Zadanie 9 – Normalizacja danych
Dataset: Oceny z 3 przedmiotów dla 20 studentów
scores = np.random.randint(40, 100, size=(20, 3))
Wymagania:
Zastosuj normalizację Min-Max per przedmiot (kolumna) → [0, 1]
Sprawdź, że min=0 i max=1 dla każdego przedmiotu
Wizualizuj rozkład przed i po normalizacji (histogramy)
Oczekiwany rezultat:
Tablica znormalizowana
2 histogramy (przed/po)

✏ Zadanie 10 – Broadcasting w praktyce
Dana tablica ocen (5 studentów x 4 egzaminy):
exams = np.array([
[78, 85, 92, 88],
[65, 72, 68, 70],
[90, 88, 95, 92],
[55, 60, 58, 62],
[82, 79, 85, 80]
])
Dodaj bonus do każdego egzaminu: [5, 10, 5, 10]
Następnie pomnóż wyniki każdego studenta przez mnożnik: [1.0, 1.1, 0.95, 1.15, 1.0]
Wymagania:
Użyj broadcastingu (bez pętli)
Wypisz wyniki przed i po

✏ Zadanie 11 – Analiza datasetu sprzedaży
Dataset: Sprzedaż 6 produktów w 30 dni
sales = np.random.randint(50, 200, size=(6, 30))
Oblicz:
Trend sprzedaży per produkt (różnica między ostatnimi 7 dniami a pierwszymi 7 dniami)
Najlepszy tydzień (dni 0-6, 7-13, 14-20, 21-27) dla całej sprzedaży
Wykres: sprzedaż per produkt w czasie (linie)
Wymagania:
Użyj slicingu do wycinania tygodni
Wizualizacja matplotlib

Zadanie 12 – Odległość Euklidesowa
Masz 2 punkty w przestrzeni 5-wymiarowej:
point_a = np.array([1, 2, 3, 4, 5])
point_b = np.array([5, 4, 3, 2, 1])
Oblicz odległość Euklidesową: sqrt(sum((a - b)^2))
Następnie oblicz macierz odległości dla 4 punktów:
points = np.random.rand(4, 5)
Wymagania:
(średnie)
Ręczna implementacja (bez gotowych funkcji)
Wynik: macierz 4x4 odległości między każdą parą punktów

13. 🧠 Zadanie 13 – Standaryzacja i outliers
Dataset: 100 wartości z rozkładu normalnego + 5 outliers
np.random.seed(42)
data = np.concatenate([np.random.randn(100) * 10 + 50,
np.array([150, -50, 200, -100, 180])])
np.random.shuffle(data)
Wymagania:
Zastosuj standaryzację (z-score)
Wykryj outliery (wartości z |z-score| > 3)
Usuń outliery i ponownie standaryzuj
Wizualizuj: przed/po (histogramy + box plot)
Oczekiwany rezultat:
Tablica bez outlierów
Wizualizacje pokazujące efekt

14. 🧠 Zadanie 14 – Symulacja Monte Carlo
Oszacuj wartość π metodą Monte Carlo:
Generuj 1,000,000 losowych punktów (x, y) w kwadracie [-1, 1] x [-1, 1]
Zlicz ile punktów znajduje się w kole (x² + y² <= 1)
π ≈ 4 * (liczba w kole / liczba total)
Wymagania:
Użyj np.random.rand() i operacji wektorowych
Bez pętli (tylko NumPy)
Wizualizuj pierwsze 10,000 punktów (kolor: w kole/poza kołem)
Oczekiwany rezultat:
Oszacowanie π (powinno być ~3.14)
Scatter plot

15. 🧠 Zadanie 15 – Convolution 1D (ręczna implementacja)
Dana tablica (sygnał) i kernel (filtr):
signal = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
kernel = np.array([0.2, 0.6, 0.2]) # Średnia ruchoma
Zaimplementuj ręcznie konwolucję 1D (bez np.convolve):
Dla każdej pozycji w sygnale zastosuj kernel
Wynik: wygładzony sygnał
Wymagania:
Użyj pętli tylko po pozycjach, operacje na kernelu wektorowe
Wizualizuj: oryginalny sygnał vs wygładzony

Zadanie 16 – Matrix multiplication (dot product)
Masz 2 macierze reprezentujące dane:
A = np.random.rand(100, 50) # 100 próbek, 50 cech
B = np.random.rand(50, 20) # 50 cech → 20 cech (transformacja)
Wymagania:
Wykonaj mnożenie macierzy: C = A @ B
Zmierz czas operacji
Porównaj z ręczną implementacją (3 zagnieżdżone pętle)
Wypisz przyspieszenie NumPy
Oczekiwany rezultat:
Macierz C (100, 20)
Porównanie czasów

17. 🧠 Zadanie 17 – Image processing basics
Utwórz obraz (tablica 100x100) z losowymi wartościami [0, 255]:
image = np.random.randint(0, 256, size=(100, 100), dtype=np.uint8)
Zastosuj:
Progowanie (thresholding): piksele < 128 → 0, >= 128 → 255
Negatyw: 255 - image
Padding: dodaj ramkę 10 pikseli (zerami) dookoła obrazu
Wymagania:
Użyj boolean indexing i np.pad()
Wizualizuj: oryginalny, progowany, negatyw, z paddingiem

Zadanie 18 – k-Nearest Neighbors (distance matrix)
Dataset: 50 punktów w 2D
np.random.seed(10)
data = np.random.rand(50, 2) * 100
Dla nowego punktu query = np.array([50, 50]):
Oblicz odległości od wszystkich 50 punktów (Euklidesowa)
Znajdź 5 najbliższych sąsiadów (indeksy i odległości)
Wizualizuj: scatter plot z zaznaczeniem query i 5-NN
Wymagania:
Broadcasting do obliczenia wszystkich odległości jednocześnie
np.argsort() do znalezienia najbliższych
(challenge)

 🧠 Zadanie 20 – Batch normalization simulation
Dataset: Mini-batch 32 próbek x 10 cech
batch = np.random.randn(32, 10) * 5 + 20
Zastosuj Batch Normalization:
Oblicz mean i std per cecha (axis=0)
Standaryzuj: (batch - mean) / std
Zastosuj scale i shift: gamma * batch_norm + beta
(gamma=2, beta=1 dla wszystkich cech)
Wymagania:
Użyj broadcasting
Sprawdź statystyki przed i po
Wykres: rozkład pierwotny vs znormalizowany (dla 1 cechy)
Oczekiwany rezultat:
Batch po normalizacji i transformacji
Histogramy przed/po